### PR TITLE
Bump axios from 0.21.4 to 1.6.2

### PR DESCRIPTION
**Pull request by ptessier**
## Description

Bump axios to resolve https://github.com/advisories/GHSA-wf5p-g6vw-rhxx

Relied on unit tests to make sure it works.

### CODE REVIEW

**Comment by ptessier** [comment]
@mprew97 Are you planning on merging my PRs? Just trying to plan if I'm waiting on this to be merged or if I should patch your package.

**Comment by mprew97** [comment]
Hey @ptessier, apologies for the delay on this. I actually was working on bundling a whole bunch of dependency issues and it's taken me longer than expected to get them tested and deployed. For the sake of time, I will test this PR first thing when I'm back this Tuesday and merge/deploy this.

**Comment by ptessier** [comment]
Thanks for the heads up. If you have some time, I also have two other PRs with small changes we patched in our repo.

**Review by mprew97 — APPROVED** [review]
Tested and approved

**Comment by mprew97** [comment]
@ptessier working on cutting the release for this and your other PRs. Thanks for your patience here. Will hopefully have it released by EOD today or tomorrow.

**Comment by ptessier** [comment]
@mprew97 Wow amazing, thanks!

**Comment by ptessier** [comment]
Seems like it might be related to the axios version that is bundled in the library.

**Pull request merged**
