### PR TITLE
MOB 9328 add JWT in response

### PR DESCRIPTION
**Pull request by hani-iterable**
## JIRA Ticket(s) if any

* [MOB-9328](https://iterable.atlassian.net/browse/MOB-9328)

## Description

> I have added JWT token to the response.

[MOB-9328]: https://iterable.atlassian.net/browse/MOB-9328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by mprew97 — COMMENTED** [review]
this is just a print statement. is this supposed to be adding additional functionality? or does print somehow add it to the response here?

**Comment by hani-iterable** [comment]
This will add token to the response.

**Review by mprew97 — CHANGES_REQUESTED** [review]
We should remove this server code altogether. You can pull down this jwt-generator [server](https://github.com/Iterable/jwt-generator), run it locally by running `docker-compose up -d`, and point the jwt-generation url there.

**Comment by hani-iterable** [comment]
@mprew97 Could you clarify what needs to be done for the MOB-9328 ticket? Based on your comment, it seems like no modifications are needed, but I want to confirm.

**Comment by hani-iterable** [comment]
@mprew97 Thank you. I have revert back server code.

**Review by mprew97 — APPROVED** [review]
thank you, @hani-iterable !!

**Pull request merged**
