### PR TITLE
fix issue -infinite loop when expiration time in jwt is wrong

### PR DESCRIPTION
**Pull request by fTariqOmnicg**
## JIRA Ticket(s) if any

* [MOB-XXXX](https://iterable.atlassian.net/browse/MOB-XXXX)

## Test Steps

### CODE REVIEW

**Review by mprew97 — APPROVED** [review]

**Comment by mprew97** [comment]
@fTariqOmnicg is this good for us to merge?

**Comment by fTariqOmnicg** [comment]
@mprew97  I have generate It and fixed it you can verify from my side its good to be merged

**Comment by mprew97** [comment]
@fTariqOmnicg good morning! I merged your other PR and this one now has conflicts. Would you mind resolving those so that we can get this merged?

**Comment by fTariqOmnicg** [comment]
@mprew97  I have resolved the conflicts its ready to merge.

**Pull request merged**
